#pragma once

#include "order_book/OrderBook.h"
#include "Trade.h"

#include <cstdint>
#include <vector>

// Handles incoming orders and matches them against
// orders already resting in the order book.
class MatchingEngine {

private:

    // The order book containing all active limit orders.
    OrderBook orderBook;

    // Stores all trades generated by successful matches.
    std::vector<Trade> trades;

    // Executes matching for an incoming BUY order.
    void matchBuy(Order& incomingOrder);

    // Executes matching for an incoming SELL order.
    void matchSell(Order& incomingOrder);

public:

    // Submits an order to the matching engine.
    void submitOrder(Order order);

    // Returns the order book.
    const OrderBook& getOrderBook() const;

    // Returns all executed trades.
    const std::vector<Trade>& getTrades() const;

    // Clears the recorded trade history.
    void clearTrades();
};