#include "matching_engine/MatchingEngine.h"

// Submits an order to the matching engine.
void MatchingEngine::submitOrder(Order order) {

    // Market and limit orders are handled by the same
    // matching process, but only LIMIT orders can rest
    // in the order book after matching.
    if (order.side == Side::BUY) {

        // Try to match the incoming BUY order
        // against existing SELL orders.
        matchBuy(order);
    }
    else {

        // Try to match the incoming SELL order
        // against existing BUY orders.
        matchSell(order);
    }

    // If quantity remains after matching and the order
    // is a LIMIT order, place the remaining quantity
    // into the order book.
    if (order.quantity > 0 &&
        order.type == OrderType::LIMIT) {

        // Add the remaining order to the appropriate
        // side of the order book.
        orderBook.addLimitOrder(order);
    }
}

// Handles an incoming BUY order.
void MatchingEngine::matchBuy(Order& incomingOrder) {

    // Match the order against the opposite side
    // of the order book.
    std::vector<Trade> generatedTrades =
        orderBook.matchOrder(incomingOrder);

    // Store every trade generated by this match.
    for (const Trade& trade : generatedTrades) {

        // Add the trade to the engine's trade history.
        trades.push_back(trade);
    }
}

// Handles an incoming SELL order.
void MatchingEngine::matchSell(Order& incomingOrder) {

    // Match the order against the opposite side
    // of the order book.
    std::vector<Trade> generatedTrades =
        orderBook.matchOrder(incomingOrder);

    // Store every trade generated by this match.
    for (const Trade& trade : generatedTrades) {

        // Add the trade to the engine's trade history.
        trades.push_back(trade);
    }
}

// Returns the current order book.
const OrderBook& MatchingEngine::getOrderBook() const {

    // Return a read-only reference to the order book.
    return orderBook;
}

// Returns all executed trades.
const std::vector<Trade>& MatchingEngine::getTrades() const {

    // Return a read-only reference to the trade history.
    return trades;
}

// Clears all recorded trades.
void MatchingEngine::clearTrades() {

    // Remove every trade from the trade history.
    trades.clear();
}