#pragma once

#include "Order.h"
#include "matching_engine/Trade.h"

#include <cstdint>
#include <deque>
#include <functional>
#include <map>
#include <vector>

// Represents the limit order book of the exchange.
class OrderBook {

private:

    // Stores buy orders grouped by price.
    //
    // std::greater<double> sorts prices from highest to lowest,
    // so the highest bid is always at the beginning.
    std::map<
        double,
        std::deque<Order>,
        std::greater<double>
    > bids;

    // Stores sell orders grouped by price.
    //
    // Default std::less ordering sorts prices from lowest to highest,
    // so the lowest ask is always at the beginning.
    std::map<
        double,
        std::deque<Order>
    > asks;

public:

    // Adds a limit order to the appropriate side of the book.
    void addLimitOrder(const Order& order);

    // Cancels an active order using its unique order ID.
    // Returns true if the order was found and cancelled.
    bool cancelOrder(std::uint64_t orderId);

    // Modifies the remaining quantity of an active order.
    // Returns true if the order was found and modified.
    bool modifyOrder(
        std::uint64_t orderId,
        std::uint64_t newQuantity
    );

    // Returns the highest bid price.
    double bestBid() const;

    // Returns the lowest ask price.
    double bestAsk() const;

    // Returns the difference between best ask and best bid.
    double spread() const;

    // Returns the midpoint between best bid and best ask.
    double midPrice() const;

    // Returns the total quantity available at a specific price.
    std::uint64_t quantityAtPrice(Side side, double price) const;

    // Returns the number of active price levels on the specified side.
    std::size_t priceLevelCount(Side side) const;

    // Matches an incoming order against the opposite side of the book.
    // Returns the trades generated by the matching process.
    std::vector<Trade> matchOrder(Order& incomingOrder);
};
